name: Build & Publish Release APK

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'tools platform-tools build-tools'
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew --no-daemon assembleRelease
    - name: Sign build
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
    - uses: actions/upload-artifact@v4
      with:
        name: StructEd Sideload APK
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
